# Generated by Django 5.2 on 2025-04-21 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='btc',
            new_name='btc_balance',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='usdt',
            new_name='usdt_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='cash',
        ),
        migrations.AddField(
            model_name='wallet',
            name='binance_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
