# Generated by Django 5.2 on 2025-04-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_btc_wallet_btc_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='binance_balance',
        ),
    ]
