# Generated by Django 5.2 on 2025-04-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_wallet_binance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_reward_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='login_streak',
            field=models.IntegerField(default=0),
        ),
    ]
